#+TITLE: Soccer
#+AUTHOR: Md Arif Shaikh
#+EMAIL: arifshaikh.astro@gmail.com

* About the package
  ~Soccer~ is an [[https://www.gnu.org/software/emacs/][Emacs]] package for getting fixtures, results etc for soccer (football) matches inside emacs. Currently it works for only Premier League (England) and La Liga (Spain) but could be easily extended to add other leagues around the world. Rank table is not supported yet but will be in the future. All data are fetched from [[https://www.scorespro.com/][scorespro]] website.
* Installation
  Currently it's not available in any package repository but one can easily install it using ~straight~ and ~use-package~
  #+BEGIN_SRC emacs-lisp
    (use-package soccer
      :straight (soccer :type git :host github :repo "md-arif-shaikh/soccer"))
  #+END_SRC
  It also need [[]] for converting source time to local time and can be added similarly
  #+BEGIN_SRC emacs-lisp
    (use-package convert-time
	:straight (convert-time :type git :host github :repo "md-arif-shaikh/emacs-convert-time"))
  #+END_SRC
  Set the source and local time zones using the abbreviations with the following examples
  #+BEGIN_SRC emacs-lisp
    (setq soccer--source-time-zone-abrv "CEST")
    (setq soccer--local-time-zone-abrv "IST")
  #+END_SRC
* Common interactive functions
  Call these using ~M-x Function~ where ~Function~ is any of the following functions

  | Functions                    | Actions                          |
  | ~soccer--fixtures-next~        | Fixture for the Next match       |
  | ~soccer--fixtures-next-5~      | Fixtures of the Next 5 matches   |
  | ~soccer--fixtures-full-in-org~ | Full fixtures saved in org file  |
  | ~soccer--results-last~         | Result of the last match         |
  | ~soccer--results-last-5~       | Results of the last 5 matches    |
  | ~soccer--results-full-in-org~  | Full list of results in org file |
